

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Port for the AMQP protocol
      - "15672:15672"  # Port for the management UI
    # This makes sure the container uses a predictable hostname
    # which is helpful for RabbitMQ.
    hostname: rabbitmq